In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [12]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [14]:
arr2d[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr2d[:, 3]

array([ 4,  8, 12, 16])

In [16]:
arr2d[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [17]:
arr2d[3,2]

15

In [18]:
arr2d[:2, 1:3] = 0

In [19]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
names = np.array(['Alex', 'Leon', 'Anthony', 'Leon', 'Alex', 'Leon', 'Kevin'])
data = np.random.randn(7, 4)

In [30]:
names

array(['Alex', 'Leon', 'Anthony', 'Leon', 'Alex', 'Leon', 'Kevin'],
      dtype='<U7')

In [40]:
data

array([[-0.15164103,  0.12206804,  0.26848974,  1.17958898],
       [-1.17926668, -0.22292224,  1.10345448, -0.26021061],
       [-0.07566523, -1.21720915,  0.28569547, -0.42630454],
       [-1.06298754, -0.26186584,  0.1355339 , -0.80163572],
       [ 2.39767153, -0.15422807, -1.96127864,  0.9061371 ],
       [ 0.06285493,  0.19794264, -0.47133705,  0.73342163],
       [-0.08415485,  1.91984752, -1.32225654, -0.00976444]])

In [26]:
names == 'Alex'

array([ True, False, False, False,  True, False, False], dtype=bool)

In [27]:
data[names == 'Alex', :]

array([[-0.15164103,  0.12206804,  0.26848974,  1.17958898],
       [ 2.39767153, -0.15422807, -1.96127864,  0.9061371 ]])

In [29]:
data[names == 'Leon']

array([[-1.17926668, -0.22292224,  1.10345448, -0.26021061],
       [-1.06298754, -0.26186584,  0.1355339 , -0.80163572],
       [ 0.06285493,  0.19794264, -0.47133705,  0.73342163]])

In [37]:
data[(names == 'Alex') | (names == 'Leon'), :]

array([[-0.15164103,  0.12206804,  0.26848974,  1.17958898],
       [-1.17926668, -0.22292224,  1.10345448, -0.26021061],
       [-1.06298754, -0.26186584,  0.1355339 , -0.80163572],
       [ 2.39767153, -0.15422807, -1.96127864,  0.9061371 ],
       [ 0.06285493,  0.19794264, -0.47133705,  0.73342163]])

In [39]:
data[:, 3] < 0

array([False,  True,  True,  True, False, False,  True], dtype=bool)

In [41]:
data[data[:, 3] < 0, :]

array([[-1.17926668, -0.22292224,  1.10345448, -0.26021061],
       [-0.07566523, -1.21720915,  0.28569547, -0.42630454],
       [-1.06298754, -0.26186584,  0.1355339 , -0.80163572],
       [-0.08415485,  1.91984752, -1.32225654, -0.00976444]])

In [42]:
data[data[:, 3] < 0, :] = 0

In [43]:
data

array([[-0.15164103,  0.12206804,  0.26848974,  1.17958898],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 2.39767153, -0.15422807, -1.96127864,  0.9061371 ],
       [ 0.06285493,  0.19794264, -0.47133705,  0.73342163],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])