In [1]:
import numpy as np

In [2]:
# user_id::item_id::rating::timestamp
# 1::1193::5::978300760
# 1::661::3::978302109
# 1::914::3::978301968
# 1::3408::4::978300275
# 1::2355::5::978824291
# 1::1197::3::978302268
# 1::1287::5::978302039
# 1::2804::5::978300719

In [3]:
data = np.loadtxt('data/movielens-1m/ratings.dat', delimiter='::', dtype=np.int64)

In [4]:
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [5]:
data.shape

(1000209, 4)

In [11]:
# calc total mean rating
mean_rating_total = data[:, 2].mean()

In [12]:
mean_rating_total

3.5815644530293169

In [14]:
# calc mean rating by user list
user_ids = np.unique(data[:, 0])

In [15]:
user_ids[:5]

array([1, 2, 3, 4, 5])

In [16]:
user_ids.shape

(6040,)

In [17]:
mean_rating_by_user_list = []
for user_id in user_ids:
    data_for_user = data[data[:, 0] == user_id, :]
    mean_rating_for_user = data_for_user[:, 2].mean()
    mean_rating_by_user_list.append([user_id, mean_rating_for_user])

In [18]:
mean_rating_by_user_list[:5]

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466]]

In [19]:
mean_rating_by_user_array = np.array(mean_rating_by_user_list, dtype=np.float32)

In [20]:
mean_rating_by_user_array[:5]

array([[ 1.        ,  4.18867922],
       [ 2.        ,  3.7131784 ],
       [ 3.        ,  3.90196085],
       [ 4.        ,  4.19047642],
       [ 5.        ,  3.14646459]], dtype=float32)

In [21]:
mean_rating_by_user_array.shape

(6040, 2)

In [22]:
np.savetxt('mean_rating_by_user.csv', mean_rating_by_user_array, fmt='%.3f', delimiter=',')