In [2]:
import numpy as np

In [3]:
data1 = [6, 7.5 ,8 ,0, 1]

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
arr1.shape

(5,)

In [7]:
data2 = [[1,2,3,4],
        [5,6,7,8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [41]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(15,40,3)

array([15, 18, 21, 24, 27, 30, 33, 36, 39])

In [22]:
arr2.dtype

dtype('int64')

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [28]:
float_arr.dtype

dtype('float64')

In [31]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [32]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [33]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [34]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [35]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [36]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [38]:
arr1 * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [39]:
arr1 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [40]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])